webapp/src/Entity/Tag.php
<?php

namespace App\Entity;

use App\Repository\TagRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TagRepository::class)]
class Tag
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'SEQUENCE')]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    /**
     * @var Collection<int, Software>
     */
    #[ORM\ManyToMany(targetEntity: Software::class, inversedBy: 'tags')]
    private Collection $Softwares;

    #[ORM\Column(nullable: true)]
    private ?int $old_comptoir_id = null;

    public function __construct()
    {
        $this->Softwares = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Software>
     */
    public function getSoftwares(): Collection
    {
        return $this->Softwares;
    }

    public function addSoftware(Software $software): static
    {
        if (!$this->Softwares->contains($software)) {
            $this->Softwares->add($software);
        }

        return $this;
    }

    public function removeSoftware(Software $software): static
    {
        $this->Softwares->removeElement($software);

        return $this;
    }

    public function getOldComptoirId(): ?int
    {
        return $this->old_comptoir_id;
    }

    public function setOldComptoirId(?int $old_comptoir_id): static
    {
        $this->old_comptoir_id = $old_comptoir_id;

        return $this;
    }
}

webapp/src/Controller/Tags/TagsDisplayController.php
<?php

namespace App\Controller\Tags;

use App\Entity\Tag;
use App\Repository\SoftwareRepository;
use App\Repository\TagRepository;
use Symfony\Bridge\Twig\Attribute\Template;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class TagsDisplayController extends AbstractController
{
    #[Route(
        path: ['/{_locale}/tag/',],
        name: 'app_tags_display_all_fix_url_typo',
        methods: ['GET', 'HEAD']
    )]
    public function allTagsPageFixUrlTypo(string $_locale): RedirectResponse
    {
        return new RedirectResponse(
            url: $this->generateUrl(
                route: 'app_tags_display_all',
                parameters: ['_locale' => "$_locale"],
            ),
            status: Response::HTTP_PERMANENTLY_REDIRECT,
        );
    }

    #[Route(
        path: ['/{_locale}/tags/',],
        name: 'app_tags_display_all',
        methods: ['GET', 'HEAD']
    )]
    #[Template('webapp/tags/display_all_tags.html.twig')]
    public function displayAllTags(string $_locale, TagRepository $tagRepository): array
    {
        $tagsCollection = $tagRepository->findAllOrderingByName();
        return [
            'lang' => $_locale,
            'tags_count'  => count($tagsCollection),
            'tags_collection' => $tagsCollection,
        ];
        // When using the #[Template] attribute, you only need to return an array with the parameters
        // to pass to the template (the attribute is the one which will create and return the Response object).
    }

    #[Route(
        path: ['/{_locale}/tag/{id}/{slug}/',],
        name: 'app_tags_display_one_tag',
        methods: ['GET', 'HEAD']
    )]
    public function displayOneTag(
        string $_locale,
        string $slug,
        Tag $tag,
    ): Response|RedirectResponse {
        if ($slug !== $tag->getSlug()) {
            $newUrl = $this->generateUrl('app_tags_display_one_tag', [
                '_locale' => $_locale,
                'id' => $tag->getId(),
                'slug' => $tag->getSlug(),
            ]);
            return new RedirectResponse(
                url: $newUrl,
                status: Response::HTTP_PERMANENTLY_REDIRECT // 308 Permanent Redirect
            );
        }
        return $this->render(
            view: 'webapp/tags/display_one_tag.html.twig',
            parameters: [
                'lang' => $_locale,
                'tag'  => $tag,
            ],
            response: new Response(),
        );
    }
}

webapp/templates/webapp/tags/display_all_tags.html.twig
{% extends 'app_base.html.twig' %}

{% block title %} {{ 'tags.display_all.head.title'|trans }} - {{ app_name }}{% endblock %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ path('app_home_i18n') }}">{{ 'breadcrumb.homepage'|trans }}</a>
            </li>
            <li class="breadcrumb-item active">
                <a href="{{ path('app_tags_display_all') }}"
                   aria-current="page">{{ 'breadcrumb.tags.list'|trans }}</a>
            </li>
        </ol>
    </nav>
    <h1>
        {{ 'tags.display_all.page.title'|trans }}
    </h1>
    <div id="tags_count">
        {{ 'tags.display_all.total_number'|trans({'%count%': tags_count }) }}
    </div>

    <ul>
        {% for tag in tags_collection %}
            <li id="tag_{{ tag.slug | replace({'.': "-"}) }}"
                class="tag_item_{{ tag.id }} badge bg-primary-subtle text-primary-emphasis rounded-pill m-1">
                <a class="tag_link"
                   href="{{ path('app_tags_display_one_tag', {'slug': tag.slug, 'id': tag.id }) }}">
                    {{ tag.name }}
                </a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

webapp/templates/webapp/tags/display_one_tag.html.twig
{% extends 'app_base.html.twig' %}
{% block title %}
    {{ 'tags.display_one.title'|trans({'%tag%': tag.name }) }} - {{ app_name }}
{% endblock %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ path('app_home_i18n') }}">{{ 'breadcrumb.homepage'|trans }}</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('app_tags_display_all') }}">{{ 'breadcrumb.tags.list'|trans }}</a>
            </li>
            <li class="breadcrumb-item active">
                <a href="{{ path('app_tags_display_one_tag', { 'slug': tag.slug, 'id': tag.id }) }}"
                   aria-current="page">{{ tag.name }}</a>
            </li>
        </ol>
    </nav>
    <h1>
        {{ 'tags.display_one.h1_start'|trans }}
        <strong>{{ tag.name }}</strong>
    </h1>
    <p>
        {{ 'tags.display_one.software_count'|trans({'%count%': tag.softwares|length, '%tag%': tag.name  }) }}
    </p>


    <ul class="software_collection">
        {% for software in tag.softwares|sort((s1, s2) => s1.slug <=> s2.slug) %}
            <li class="software_{{ software.id }}">
                <a href="{{ path(
                    'app_anonymous_software_display_one_software',
                    {'id': software.id, 'slug': software.slug }
                ) }}">{{ software.name }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}