webapp/src/Entity/User.php
<?php

/*
 * This file is part of the Comptoir-du-Libre software.
 * <https://gitlab.adullact.net/Comptoir/comptoir-du-libre>
 *
 * Copyright (c) ADULLACT   <https://adullact.org>
 *               Association des Développeurs et Utilisateurs de Logiciels Libres
 *               pour les Administrations et les Collectivités Territoriales
 *
 * Comptoir-du-Libre is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this software. If not, see <https://www.gnu.org/licenses/agpl-3.0.en.html>.
 */

declare(strict_types=1);

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'SEQUENCE')]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\OneToOne(mappedBy: 'usedBy', cascade: ['persist', 'remove'])]
    private ?UserToken $userToken = null;

    #[ORM\Column(nullable: true)]
    private ?int $old_comptoir_id = null;

    #[ORM\Column(nullable: true)]  // TODO remove nullable
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)] // TODO remove nullable
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $last_passowrd_update = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUserToken(): ?UserToken
    {
        return $this->userToken;
    }

    public function setUserToken(?UserToken $userToken): static
    {
        // set the owning side of the relation if necessary
        if (!is_null($userToken) && $userToken->getUsedBy() !== $this) {
            $userToken->setUsedBy($this);
        }
        $this->userToken = $userToken;

        return $this;
    }

    public function getOldComptoirId(): ?int
    {
        return $this->old_comptoir_id;
    }

    public function setOldComptoirId(?int $old_comptoir_id): static
    {
        $this->old_comptoir_id = $old_comptoir_id;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getLastPassowrdUpdate(): ?\DateTimeInterface
    {
        return $this->last_passowrd_update;
    }

    public function setLastPassowrdUpdate(?\DateTimeInterface $last_passowrd_update): static
    {
        $this->last_passowrd_update = $last_passowrd_update;

        return $this;
    }
}

webapp/src/Form/User/ResetPasswordRequestFormType.php
<?php

/*
 * This file is part of the Comptoir-du-Libre software.
 * <https://gitlab.adullact.net/Comptoir/comptoir-du-libre>
 *
 * Copyright (c) ADULLACT   <https://adullact.org>
 *               Association des Développeurs et Utilisateurs de Logiciels Libres
 *               pour les Administrations et les Collectivités Territoriales
 *
 * Comptoir-du-Libre is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this software. If not, see <https://www.gnu.org/licenses/agpl-3.0.en.html>.
 */

declare(strict_types=1);

namespace App\Form\User;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Email;

class ResetPasswordRequestFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class, [
                'label' => 'forgot_password.request.form.label.email',
                'help' => 'forgot_password.request.form.label.email.help',
                'constraints' => [
                    new NotBlank([
                        'message' => 'common.validator.help.field.error.required',
                    ]),
                    new Email([
                        'mode' => 'html5',
                        'message' => 'common.validator.help.email.error.not-valid',
                    ]),
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // enable/disable CSRF protection for this form
            'csrf_protection' => true,
            // the name of the hidden HTML field that stores the token
            'csrf_field_name' => 'csrf_token_ResetPasswordRequest',
            // an arbitrary string used to generate the value of the token
            // using a different string for each form improves its security
            'csrf_token_id'   => 'task_ResetPasswordRequestFormType',
        ]);
    }
}

webapp/src/Controller/User/LoginController.php
<?php

/*
 * This file is part of the Comptoir-du-Libre software.
 * <https://gitlab.adullact.net/Comptoir/comptoir-du-libre>
 *
 * Copyright (c) ADULLACT   <https://adullact.org>
 *               Association des Développeurs et Utilisateurs de Logiciels Libres
 *               pour les Administrations et les Collectivités Territoriales
 *
 * Comptoir-du-Libre is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this software. If not, see <https://www.gnu.org/licenses/agpl-3.0.en.html>.
 */

declare(strict_types=1);

namespace App\Controller\User;

use App\Entity\UserToken;
use App\Form\User\ResetPasswordRequestFormType;
use App\Form\User\ResetPasswordFormType;
use App\Repository\UserRepository;
use App\Repository\UserTokenRepository;
use App\Service\Mailer\MailerPasswordResetLink;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mime\Address;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGenerator;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Contracts\Translation\TranslatorInterface;

#[\Symfony\Component\Routing\Attribute\Route(
    requirements: [
        '_locale' => 'en|fr',
    ],
)]
class LoginController extends AbstractController
{
    #[Route(
        path: '/{_locale}/account/login',
        name: 'app_account_login',
        methods: ['GET', 'POST']
    )]
    public function login(
        AuthenticationUtils $authenticationUtils,
        AuthorizationCheckerInterface $authChecker,
    ): Response {
        if (true === $authChecker->isGranted('ROLE_USER')) {
            return $this->redirectToRoute(route: 'app_user_account', status: Response::HTTP_SEE_OTHER);
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();

        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('user/login.html.twig', [
            'last_username' => $lastUsername,
            'error'         => $error,
        ]);
    }

    #[Route(
        path: '/{_locale}/account/logout',
        name: 'app_account_logout',
        methods: ['GET']
    )]
    public function logout(): never
    {
        // controller can be blank: it will never be called!
        throw new \Exception('Don\'t forget to activate logout in security.yaml');
    }

    #[Route(
        path: '/{_locale}/account/forgot-password',
        name: 'app_account_forgot_password_request',
        methods: ['GET', 'POST']
    )]
    public function forgotPassword(
        Request $request,
        UserRepository $userRepository,
        UserTokenRepository $userTokenRepository,
        TokenGeneratorInterface $tokenGenerator,
        MailerPasswordResetLink $mailer,
        AuthorizationCheckerInterface $authChecker,
    ): Response {
        if (true === $authChecker->isGranted('ROLE_USER')) {
            return $this->redirectToRoute(route: 'app_user_account', status: Response::HTTP_SEE_OTHER);
        }

        $tokenLifetime = $this->getParameter('app.user_config.reset_password_token_lifetime');
        $form = $this->createForm(ResetPasswordRequestFormType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $userRepository->findOneByEmail($form->get('email')->getData());
            if ($user) {
                // Update or create reset password token
                $now = new \DateTimeImmutable();
                $validTo = $now->add(\DateInterval::createFromDateString("${tokenLifetime} seconds"));
                $token = $user->getUserToken();
                if (is_null($token)) {
                    $token = new UserToken();
                }
                $token->setToken($tokenGenerator->generateToken());
                $token->setCreatedAt($now);
                $token->setValidTo($validTo);
                $token->setUsedBy($user);
                $userTokenRepository->save($token, true);
                $resetPassowrdUrl = $this->generateUrl(
                    route:'app_account_forgot_password_new-password',
                    parameters:['tokenKey' => $token->getToken()],
                    referenceType: UrlGenerator::ABSOLUTE_URL
                );

                $emailSent = false; // TODO use this in template
                try {
                    $mailer->sendPasswordResetLink(
                        msgFrom: new Address($this->getParameter('app.email.from')),
                        msgTo: new Address($user->getEmail()),
                        resetPasswordUrl: $resetPassowrdUrl
                    );
                    $emailSent = true;
                } catch (\Throwable $e) {
                    // catch         Symfony\Component\Mailer\Exception\TransportException
                    // but not catch Symfony\Component\Mailer\Exception\InvalidArgumentException
                    //               Symfony\Component\Mailer\Exception\UnsupportedSchemeException
                    $errorMsg = $e->getMessage();  // TODO log error
                }
                // complexify a time attack: add a time pause varying between 100 and 300 milliseconds
                usleep(microseconds: rand(100_000, 300_000));
            } else {
                // complexify a time attack: add a time pause varying between 150 and 350 milliseconds
                usleep(microseconds: rand(150_000, 350_000));
            }

            return $this->render('user/forgot_passord_request_result.html.twig', [
                'forgotPasswordForm' => $form->createView(),
            ]);
        }

        // Display empty form or form with error messages
        return $this->render('user/forgot_passord_request_form.html.twig', [
            'forgotPasswordForm' => $form->createView(),
        ]);
    }

    #[Route(
        path:'/{_locale}/account/forgot-password/t/{tokenKey}',
        name: 'app_account_forgot_password_new-password',
        methods: ['GET', 'POST']
    )]
    public function forgotPasswordCheckToken(
        string $tokenKey,
        Request $request,
        UserRepository $userRepository,
        UserTokenRepository $tokenRepository,
        UserPasswordHasherInterface $userPasswordHasher,
        TranslatorInterface $translator,
        AuthorizationCheckerInterface $authChecker,
    ): Response {
        if (true === $authChecker->isGranted('ROLE_USER')) {
            return $this->redirectToRoute(route: 'app_user_account', status: Response::HTTP_SEE_OTHER);
        }

        $minPasswordLength = $this->getParameter('app.user_config.min_password_length');
        $form = $this->createForm(
            type: ResetPasswordFormType::class,
            options: ['min_password_length' => $minPasswordLength]
        );
        $form->handleRequest($request);

        $validToken = true;
        $token = $tokenRepository->findOneByToken($tokenKey);
        $now = new \DateTimeImmutable();
        if (is_null($token)) {
            $validToken = false;
        } elseif (($now->getTimestamp() - $token->getValidTo()->getTimestamp() ) > 0) {
            $validToken = false;
            $tokenRepository->remove($token, true);
        }

        if ($validToken === false) {
            return $this->render('user/forgot_passord_not_valid_token.html.twig', []);
        }

        // Update user password
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $token->getUsedBy();

            // Encode the plain password
            $user->setPassword($userPasswordHasher->hashPassword($user, $form->get('newPlainPassword')->getData()));

            // Update user account datetimes
            $user->setLastPassowrdUpdate($now);
            $user->setUpdatedAt($now);

            $userRepository->save($user, true);
            $tokenRepository->remove($token, true);
            $successMsg =  $translator->trans('user.change_password.success');
            $this->addFlash('success', "$successMsg");
            return $this->redirectToRoute('app_account_login', [], Response::HTTP_SEE_OTHER);
        }

        // Display empty form or form with error messages
        return $this->render('user/forgot_passord_form.html.twig', [
            'forgotPasswordForm' => $form->createView(),
        ]);
        // encode the plain password
//            $user->setPassword($userPasswordHasher->hashPassword($user, $form->get('newPlainPassword')->getData()));
//            $userRepository->save($user, true);
//            $successMsg =  $translator->trans('user.change_password.success');
//            $this->addFlash('success', "$successMsg");
//            return $this->redirectToRoute('app_user_account', [], Response::HTTP_SEE_OTHER);
    }
}

webapp/templates/user/account.html.twig
{% extends 'app_base.html.twig' %}

{% block title %}{{ 'user.account.head.title'|trans }} - {{ app_name }}{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ path('app_home_i18n') }}">{{ 'breadcrumb.homepage'|trans }}</a>
            </li>
            <li class="breadcrumb-item active">
                <a href="{{ path('app_user_account') }}"
                   aria-current="page">{{ 'breadcrumb.user.account'|trans }}</a>
            </li>
        </ol>
    </nav>

    <h1> {{ 'user.account.page.title'|trans }} </h1>
{#    <div class="col-md-6">#}
{#        <table  class="table table-hover table-dark table-striped">#}
{#            <thead>#}
{#            <tr>#}
{#                <th scope="col">{{ 'user.account.data-title.email'|trans }} </th>#}
{#                <th scope="col">{{ 'user.account.data-title.roles'|trans }} </th>#}
{#            </tr>#}
{#            </thead>#}
{#            <tbody class="table-group-divider">#}
{#            <tr>#}
{#                <td><strong>{{ app.user.email }}</strong></td>#}
{#                <td> {{ 'common.help.comming-soon'|trans }} </td>#}
{#            </tr>#}
{#            </tbody>#}
{#        </table>#}
{#    </div>#}

    <nav>
        <ul class="icon-list ps-0">
            <li class="d-flex align-items-start mb-1">
                {{ 'user.account.link.change_account_email'|trans }}
            </li>
            <li class="d-flex align-items-start mb-1">
                <a id="user_change-password_link" href="{{ path('app_user_account_change_password') }}">
                    {{ 'user.account.link.change_password'|trans }}
                </a>
            </li>
        </ul>
    </nav>

    <div class="col-md-12">
        <table  class="table table-sm table-borderless mt-3">
            <tr>
                <th scope="row"> {{ 'user.account.data-title.email'|trans }} </th>
                <td>    <strong id="qa_user-account_user-email">{{ app.user.email }}</strong>   </td>
            </tr>
            <tr>
                <th scope="row"> {{ 'user.account.data-title.roles'|trans }} </th>
                <td>    {{ 'common.help.comming-soon'|trans }}  </td>
            </tr>
            <tr>
                <th scope="row"> {{ 'user.account.data-title.created_at'|trans }} </th>
                <td>
                    {{ app.user.createdAt|format_datetime('full', 'short', locale=_locale) }}
                </td>
            </tr>
            <tr>
                <th scope="row"> {{ 'user.account.data-title.updated_at'|trans }} </th>
                <td>
                    {{ app.user.updatedAt|format_datetime('medium', 'short', locale=_locale) }}
                </td>
            </tr>
            <tr>
                <th scope="row"> {{ 'user.account.data-title.last_update_password'|trans }} </th>
                <td>
                    {% if app.user.lastPassowrdUpdate  is not null %}
                        {{ app.user.lastPassowrdUpdate|format_datetime('short', 'short', locale=_locale) }}
                    {% else %}
                        TODO: add message if lastPassowrdUpdate is null <br>
                        {% if app.user.updatedAt|date('U') < '2020-12-31'|date('U') %}
                            OLDER
                        {% else %}
                            NOT SO OLDER
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>

    <div class="debug">
        <h2>DEBUG staging <-- TODO add staging FLAG</h2>
        {% if app.user.oldComptoirId  is not null %}
            <hr>
            <small>
                {{ 'recette.debug.user.old_id'|trans }} <-- TODO add staging FLAG <br>
                <ul>
                    <li><a target="_blank" href="/fr/users/{{ app.user.oldComptoirId  }}">/fr/users/{{ app.user.oldComptoirId  }}</a></li>
                    <li><a target="_blank" href="/en/users/{{ app.user.oldComptoirId  }}">/en/users/{{ app.user.oldComptoirId  }}</a></li>
                    <li><a target="_blank" href="https://comptoir-du-libre.org/fr/users/{{ app.user.oldComptoirId  }}">https://comptoir-du-libre.org/fr/users/{{ app.user.oldComptoirId  }}</a></li>
                    <li><a target="_blank" href="https://comptoir-du-libre.org/en/users/{{ app.user.oldComptoirId  }}">https://comptoir-du-libre.org/en/users/{{ app.user.oldComptoirId  }}</a></li>
                </ul>
            </small>
        {% else %}
            NOT OLD USER
        {% endif %}
    </div>



{% endblock %}

webapp/templates/user/account_change-password.html.twig
{% extends 'app_base.html.twig' %}
{% form_theme changePasswordForm 'bootstrap_5_layout.html.twig' %}

{% block title %}{{ 'user.change_password.head.title'|trans }} - {{ app_name }}{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ path('app_home_i18n') }}">{{ 'breadcrumb.homepage'|trans }}</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('app_user_account') }}">{{ 'breadcrumb.user.account'|trans }}</a>
            </li>
            <li class="breadcrumb-item active">
                <a href="{{ path('app_user_account_change_password') }}"
                   aria-current="page">{{ 'breadcrumb.user.account.change_password'|trans }}</a>
            </li>
        </ol>
    </nav>

    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="flash-{{ label }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}

    <div class="mb-5">
        <h1> {{ 'user.change_password.page.title'|trans }} </h1>
        {{ form_start(changePasswordForm) }}

            <div class="my-custom-class-for-errors">
                {{ form_errors(changePasswordForm) }}
            </div>
            <fieldset class="mt-4 mb-4 ">
                <legend class="text-xl text-bg-dark px-2">
                    {{ 'user.change_password.form.legend.current-password'|trans }}
                </legend>
                {% if isInvalidCurrentPassword == true %}
                    {{ form_row(changePasswordForm.currentPlainPassword, {'attr': {'class': 'is-invalid'}})  }}
                    <span class="invalid-feedback d-block">
                        {{ 'common.validator.help.password.error.not-valid-current-password'|trans }}
                    </span>
                {% else %}
                    {{ form_row(changePasswordForm.currentPlainPassword)  }}
                {% endif %}

            </fieldset>
            <fieldset class="mt-4 mb-4 ">
                <legend class="text-xl text-bg-dark px-2">
                    {{ 'user.change_password.form.legend.new-password'|trans }}
                </legend>
                {{ form_row(changePasswordForm.newPlainPassword)  }}
            </fieldset>
            <button id="user-changePasswordForm_submit" class="btn btn-primary">
                {{ 'user.change_password.form.submit'|trans|raw }}
            </button>
        {{ form_end(changePasswordForm) }}
    </div>


{% endblock %}

webapp/templates/user/forgot_passord_form.html.twig
{% extends 'app_base.html.twig' %}
{% form_theme forgotPasswordForm 'bootstrap_5_layout.html.twig' %}

{% block title %} {{ 'forgot_password.head.title'|trans }} - {{ app_name }}{% endblock %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ path('app_home_i18n') }}">{{ 'breadcrumb.homepage'|trans }}</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('app_account_login') }}">{{ 'breadcrumb.user.login'|trans }}</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('app_account_forgot_password_request') }}">{{ 'breadcrumb.user.lost_password.form'|trans }}</a>
            </li>
        </ol>
    </nav>


    <div  class="col-md-7">
        <h1>
            {{ 'forgot_password.page.title'|trans }}
        </h1>
        {{ form_start(forgotPasswordForm) }}
        {{ form_widget(forgotPasswordForm) }}
        <button id="public_forgotPassword_newPasswordForm_submit" class="btn btn-primary">
            {{ 'forgot_password.form.submit'|trans|raw }}
        </button>
        {{ form_end(forgotPasswordForm) }}
    </div>

{% endblock %}

webapp/templates/user/forgot_passord_not_valid_token.html.twig
{% extends 'app_base.html.twig' %}

{% block title %} {{ 'forgot_password.not-voalid-token.head.title'|trans }} - {{ app_name }}{% endblock %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ path('app_home_i18n') }}">{{ 'breadcrumb.homepage'|trans }}</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('app_account_login') }}">{{ 'breadcrumb.user.login'|trans }}</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('app_account_forgot_password_request') }}">{{ 'breadcrumb.user.lost_password.form'|trans }}</a>
            </li>
        </ol>
    </nav>

    <div  class="col-md-9">
        <h1>
            {{ 'forgot_password.not-voalid-token.page.title'|trans }}
        </h1>
        <p id="error_forgot-password_not-voalid-token" class="alert alert-danger">
            {{ 'forgot_password.not-voalid-token.error_msg'|trans }}
        </p>
        <p>
            {{ 'forgot_password.not-voalid-token.call_to_action'|trans }}
            <a href="{{ path('app_account_forgot_password_request') }}">
                {{ 'forgot_password.not-voalid-token.call_to_action.link'|trans }}</a>.
        </p>
    </div>

{% endblock %}

webapp/templates/user/forgot_passord_request_form.html.twig
{% extends 'app_base.html.twig' %}
{% form_theme forgotPasswordForm 'bootstrap_5_layout.html.twig' %}

{% block title %} {{ 'forgot_password.request.head.title'|trans }} - {{ app_name }}{% endblock %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ path('app_home_i18n') }}">{{ 'breadcrumb.homepage'|trans }}</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('app_account_login') }}">{{ 'breadcrumb.user.login'|trans }}</a>
            </li>
            <li class="breadcrumb-item active">
                <a href="{{ path('app_account_forgot_password_request') }}"
                   aria-current="page">{{ 'breadcrumb.user.lost_password.form'|trans }}</a>
            </li>
        </ol>
    </nav>

    <div  class="col-md-7">
        <h1>
            {{ 'forgot_password.request.page.title'|trans }}
        </h1>
        {{ form_start(forgotPasswordForm) }}
        {{ form_widget(forgotPasswordForm) }}
        <button id="public_forgotPassword_requestForm_submit" class="btn btn-primary">
            {{ 'forgot_password.request.form.submit'|trans|raw }}
        </button>
        {{ form_end(forgotPasswordForm) }}
    </div>

{% endblock %}