webapp/src/Entity/Software.php
<?php

namespace App\Entity;

use App\Repository\SoftwareRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SoftwareRepository::class)]
class Software
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'SEQUENCE')]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 125)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $websiteUrl = null;

    #[ORM\Column(length: 255)]
    private ?string $repositoryUrl = null;

    #[ORM\Column(length: 150)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(nullable: true, unique: true)]
    private ?int $old_comptoir_id = null;

    /**
     * @var Collection<int, SoftwareScreenshot>
     */
    #[ORM\OneToMany(targetEntity: SoftwareScreenshot::class, mappedBy: 'software', orphanRemoval: true)]
    private Collection $softwareScreenshots;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $old_license_name = null;

    /**
     * @var Collection<int, SoftwareI18n>
     */
    #[ORM\OneToMany(targetEntity: SoftwareI18n::class, mappedBy: 'software', orphanRemoval: true)]
    private Collection $softwareI18ns;

    /**
     * @var Collection<int, Tag>
     */
    #[ORM\ManyToMany(targetEntity: Tag::class, mappedBy: 'Softwares')]
    private Collection $tags;

    public function __construct()
    {
        $this->softwareScreenshots = new ArrayCollection();
        $this->softwareI18ns = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getWebsiteUrl(): ?string
    {
        return $this->websiteUrl;
    }

    public function setWebsiteUrl(?string $websiteUrl): static
    {
        $this->websiteUrl = $websiteUrl;

        return $this;
    }

    public function getRepositoryUrl(): ?string
    {
        return $this->repositoryUrl;
    }

    public function setRepositoryUrl(string $repositoryUrl): static
    {
        $this->repositoryUrl = $repositoryUrl;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getOldComptoirId(): ?int
    {
        return $this->old_comptoir_id;
    }

    public function setOldComptoirId(?int $old_comptoir_id): static
    {
        $this->old_comptoir_id = $old_comptoir_id;

        return $this;
    }

    /**
     * @return Collection<int, SoftwareScreenshot>
     */
    public function getSoftwareScreenshots(): Collection
    {
        return $this->softwareScreenshots;
    }

    public function addSoftwareScreenshot(SoftwareScreenshot $softwareScreenshot): static
    {
        if (!$this->softwareScreenshots->contains($softwareScreenshot)) {
            $this->softwareScreenshots->add($softwareScreenshot);
            $softwareScreenshot->setSoftware($this);
        }

        return $this;
    }

    public function removeSoftwareScreenshot(SoftwareScreenshot $softwareScreenshot): static
    {
        if ($this->softwareScreenshots->removeElement($softwareScreenshot)) {
            // set the owning side to null (unless already changed)
            if ($softwareScreenshot->getSoftware() === $this) {
                $softwareScreenshot->setSoftware(null);
            }
        }

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    public function getOldLicenseName(): ?string
    {
        return $this->old_license_name;
    }

    public function setOldLicenseName(?string $old_license_name): static
    {
        $this->old_license_name = $old_license_name;

        return $this;
    }

    /**
     * @return Collection<int, SoftwareI18n>
     */
    public function getSoftwareI18ns(): Collection
    {
        return $this->softwareI18ns;
    }

    public function addSoftwareI18n(SoftwareI18n $softwareI18n): static
    {
        if (!$this->softwareI18ns->contains($softwareI18n)) {
            $this->softwareI18ns->add($softwareI18n);
            $softwareI18n->setSoftware($this);
        }

        return $this;
    }

    public function removeSoftwareI18n(SoftwareI18n $softwareI18n): static
    {
        if ($this->softwareI18ns->removeElement($softwareI18n)) {
            // set the owning side to null (unless already changed)
            if ($softwareI18n->getSoftware() === $this) {
                $softwareI18n->setSoftware(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): static
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
            $tag->addSoftware($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): static
    {
        if ($this->tags->removeElement($tag)) {
            $tag->removeSoftware($this);
        }

        return $this;
    }
}

webapp/src/Controller/Software/SoftwareDisplayController.php
<?php

/*
 * This file is part of the Comptoir-du-Libre software.
 * <https://gitlab.adullact.net/Comptoir/comptoir-du-libre>
 *
 * Copyright (c) ADULLACT   <https://adullact.org>
 *               Association des Développeurs et Utilisateurs de Logiciels Libres
 *               pour les Administrations et les Collectivités Territoriales
 *
 * Comptoir-du-Libre is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this software. If not, see <https://www.gnu.org/licenses/agpl-3.0.en.html>.
 */

declare(strict_types=1);

namespace App\Controller\Software;

use App\Entity\Software;
use App\Repository\SoftwareI18nRepository;
use App\Repository\SoftwareRepository;
use App\Repository\SoftwareScreenshotRepository;
use Nelmio\SecurityBundle\ExternalRedirect\ExternalRedirectResponse;
use Symfony\Bridge\Twig\Attribute\Template;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\Slugger\AsciiSlugger;

#[Route(
    requirements: [
        '_locale' => 'en|fr',
    ],
)]
class SoftwareDisplayController extends AbstractController
{
    #[Route(
        path: [
            'en' => '/{_locale}/software/{id}/{slug}/',
            'fr' => '/{_locale}/logiciel/{id}/{slug}/',
        ],
        name: 'app_anonymous_software_display_one_software',
        methods: ['GET', 'HEAD']
    )]
    public function displayOneSoftware(
        string $_locale,
        string $slug,
        Software $software,
        SoftwareScreenshotRepository $screenshotRepository,
        SoftwareI18nRepository $softwareI18nRepository,
    ): Response|RedirectResponse {
        if ($slug !== $software->getSlug()) {
            $newUrl = $this->generateUrl('app_anonymous_software_display_one_software', [
                '_locale' => $_locale,
                'id' => $software->getId(),
                'slug' => $software->getSlug(),
            ]);
            return new RedirectResponse(
                url: $newUrl,
                status: Response::HTTP_PERMANENTLY_REDIRECT // 308 Permanent Redirect
            );
        }
        $screenshots = $screenshotRepository->findBy(['software' => $software->getId()]);
        $softwareDescription = $softwareI18nRepository->findOneBy([
            'software' => $software->getId(),
            'locale' => $_locale,
            'type' => 1
        ]); // @@@TODO improve it: if empty --> get other local
        return $this->render(
            view: 'webapp/software/display_one_software.html.twig',
            parameters: [
                '_locale' => $_locale,
                'software' => $software,
                'screenshots' => $screenshots,
                'softwareDescription' => $softwareDescription,
            ],
            response: new Response(),
        );
    }


    #[Route(
        path: [
            'en' => '/{_locale}/software/',
            'fr' => '/{_locale}/logiciels/',
        ],
        name: 'app_anonymous_software_display_all_software',
        methods: ['GET', 'HEAD']
    )]
    #[Template('webapp/software/display_all_software.html.twig')]
    public function displayAllSoftware(string $_locale, SoftwareRepository $softwareRepository): array
    {
        $softwareCollection = $softwareRepository->findAllOrderingByName();
        return [
            '_locale' => $_locale,
            'software_count'  => count($softwareCollection),
            'software_collection' => $softwareCollection,
        ];
        // When using the #[Template] attribute, you only need to return an array with the parameters
        // to pass to the template (the attribute is the one which will create and return the Response object).
    }
}

webapp/templates/webapp/software/display_all_software.html.twig
{% extends 'app_base.html.twig' %}

{% block title %} {{ 'software.display_all.head.title'|trans }} - {{ app_name }}{% endblock %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ path('app_home_i18n') }}">{{ 'breadcrumb.homepage'|trans }}</a>
            </li>
            <li class="breadcrumb-item active">
                <a href="{{ path('app_anonymous_software_display_all_software') }}"
                   aria-current="page">{{ 'breadcrumb.software.list'|trans }}</a>
            </li>
        </ol>
    </nav>
    <h1>
        {{ 'software.display_all.page.title'|trans }}
    </h1>
    {{ 'software.display_all.total_number'|trans({'%count%': software_count|format_number(locale: _locale) }) }}
    <ul class="software_collection">
    {% for software in software_collection %}
        <li class="software_{{ software.id }}">
            <a href="{{ path(
                'app_anonymous_software_display_one_software',
                {'id': software.id, 'slug': software.slug }
            ) }}">{{ software.name }}</a>
        </li>
    {% endfor %}
    </ul>

{% endblock %}

webapp/templates/webapp/software/display_one_software.html.twig
{% extends 'app_base.html.twig' %}

{% block title %} {{ 'software.display.head.title'|trans({
    '%software%': software.name,
    '%app_name%': app_name,
}) }}{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ path('app_home_i18n') }}">{{ 'breadcrumb.homepage'|trans }}</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('app_anonymous_software_display_all_software') }}">{{ 'breadcrumb.software.list'|trans }}</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                <a href="{{ path(
                    'app_anonymous_software_display_one_software',
                    {'id': software.id, 'slug': software.slug }
                ) }}">{{ software.name }}</a>
            </li>
        </ol>
    </nav>

    <h1>
        {{ software.name }}
    </h1>

<!--
{#    {% cspstyle %}#}
    <style>
        .size-logo-overview {
            height: 10em;
        }
        .size-logo-overview img {
            height: auto;
            max-height: 10em;
        }
    </style>
{#    {% endcspstyle %}#}
-->
    <div class="size-logo-overview">
        {% if software.logo|length > 0 %}
            <img   loading="lazy"
                   class="qa_software_logo"
                   src="/images/content/software/{{ software.id }}/logo/{{  software.logo }}"
                   alt="{{ software.name }}">
        {% else %}
            <img   loading="lazy"
                   class="qa_software_logo qa_software_logo_placeholder"
                   src="/images/placeholder_software.png"
                   alt="">
        {% endif %}
    </div>

    <div class="col-md-12 mt-5">
        <table  class="qa_table_data table table-sm table-borderless mt-3">
            <tr>
                <th scope="row"> {{ 'software.display.website_url'|trans }} </th>
                <td>
                    <a class="qa_software_website-link"
                       href="{{ software.websiteUrl }}">{{ software.websiteUrl }}</a>
                </td>
            </tr>
            <tr>
                <th scope="row">  {{ 'software.display.repository_url'|trans }}  </th>
                <td>
                    <a class="qa_software_repository-link"
                       href="{{ software.repositoryUrl }}">{{ software.repositoryUrl }}</a>
                </td>
            </tr>
            <tr>
                <th scope="row"> {{ 'software.display.license'|trans }} </th>
                <td class="qa_software_license">    {{ software.oldLicenseName }}   </td>
            </tr>
        </table>
    </div>

    {% if softwareDescription %}
        <div  class="qa_software_description">
            {{ softwareDescription.text | sanitize_html('user-data_remove_html')
                                        | markdown_to_html
                                        | sanitize_html('user-data_markdown-sanitizer') }}
        </div>

        {% if is_granted('IS_AUTHENTICATED_FULLY') and  is_granted('ROLE_SUPERADMIN') %}
            <!-- ///// DEBUG - markdown_to_html + sanitize_html ////////////////////////////////////////////// -->
            <div class="debug">
                <h6>  nl2br </h6>
                {{ softwareDescription.text | nl2br }}
            </div>
            <div class="debug">
                <h6> markdown_to_html
                    <br> | sanitize_html()  </h6>
                {{ softwareDescription.text | markdown_to_html | sanitize_html() }}
            </div>
            <div class="debug">
                <h6> markdown_to_html
                    <br> | sanitize_html('user-data_markdown-sanitizer')  </h6>
                {{ softwareDescription.text | markdown_to_html | sanitize_html('user-data_markdown-sanitizer') }}
            </div>
            <div class="debug">
                <h6> sanitize_html('user-data_remove_html')
                    <br> | markdown_to_html
                    <br> | sanitize_html('user-data_markdown-sanitizer')  </h6>
                {{ softwareDescription.text | sanitize_html('user-data_remove_html')
                | markdown_to_html
                | sanitize_html('user-data_markdown-sanitizer') }}
            </div>

            <!-- ///// DEBUG END - markdown_to_html + sanitize_html ////////////////////////////////////////////// -->
        {% endif %}
    {% endif %}

    <div class="col-md-8 mt-5">
        <details>
            <summary>{{ 'software.display.publishing_info.summary'|trans }}</summary>
            <table  class="qa_table_data table table-sm table-bordered mt-3">
                <tr>
                    <th scope="row"> {{ 'software.display.publishing_info.created_at'|trans }} </th>
                    <td>
                        {{ software.createdAt|format_datetime('full', 'short', locale=_locale) }}
                    </td>
                </tr>
                <tr>
                    <th scope="row"> {{ 'software.display.publishing_info.updated_at'|trans }} </th>
                    <td>
                        {{ software.updatedAt|format_datetime('full', 'short', locale=_locale) }}
                    </td>
                </tr>
            </table>
        </details>
    </div>



    <!-- TAGS ------------------------------------------------------------- -->
    {% if software.tags|length > 0 %}
        <hr>
        {{ 'software.display.tags_collection'|trans }}
        <ul class="tags_collection">
            {% for tag in software.tags %}
                <li class="tag_item_{{ tag.id }}  badge bg-primary-subtle text-primary-emphasis rounded-pill">
                    <a href="{{ path('app_tags_display_one_tag', {'slug': tag.slug, 'id': tag.id }) }}">
                        {{ tag.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    <!-- SCREENSHOTS ------------------------------------------------------------- -->
    {% if screenshots|length > 0 %}
        <h2>
            {{ 'software.display.screenshots.title'|trans({'%software%': software.name,}) }}
        </h2>
        <div class="container screenshot_thumbnail-list " >
            <ul class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for screenshot in screenshots %}
                    <li class="col">
                        <a href="/images/content/software/{{ software.id }}/screenshots/{{  screenshot.fileName }}">
                            <img   loading="lazy"
                                   class="card-img-top screenshot_thumbnail"
                                   src="/images/content/software/{{ software.id }}/screenshots/{{  screenshot.fileName }}"
                                   alt="screenshot {{  screenshot.fileName }}">
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}


{% endblock %}